apiVersion: v2
name: airflow
version: 1.12.0
appVersion: 2.8.1
description: The official Helm chart to deploy Apache Airflow, a platform to
  programmatically author, schedule, and monitor workflows
home: https://airflow.apache.org/
sources:
  - https://github.com/apache/airflow
icon: https://airflow.apache.org/images/airflow_dark_bg.png
dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled